Get pfp
keepid/keepid_server pull request #39
Opened 2020-09-19 04:03 UTC by cccyyyr

Load-pfp outputs a stream.

2020-10-07 19:46 UTC, crchong1 commented
@cccyyyr what is the status of this PR?

2020-10-14 03:14 UTC, kofmangregory commented on src/main/Config/Message.java
> +
Can you add a comment describing what this class does?

2020-10-14 03:14 UTC, kofmangregory commented on src/main/Config/Service.java
> +
Add a comment to explain what this class is for.

2020-10-14 03:30 UTC, kofmangregory requested changes

2020-10-14 03:30 UTC, kofmangregory commented on src/main/ForFun/Sub.java
> +package ForFun;
Should this file be deleted?

2020-10-14 03:30 UTC, kofmangregory commented on src/main/ForFun/Super.java
> +package ForFun;
Should this file be deleted?

2020-10-14 03:30 UTC, kofmangregory commented on src/test/OrgTests/OrganizationJWTTests.java
> +  //  @Test
Can we delete all commented out code? Here and elsewhere in the PR.

2020-10-14 03:30 UTC, kofmangregory commented on src/main/User/UserController.java
> +    GridFSFile grid_out = gridBucket.find(filter).first();
camelCase

2020-10-14 03:30 UTC, kofmangregory commented on src/main/User/UserController.java
> +    GridFSBucket gridBucket = GridFSBuckets.create(db, "pfp");
Can you add some comments about what these methods do?

2020-10-14 03:30 UTC, kofmangregory commented on src/main/User/UserController.java
> +            .chunkSizeBytes(100000)
Can this constant be declared at the top of the file?

2020-10-14 03:30 UTC, kofmangregory commented on src/main/User/UserController.java
> +  public void uploadPfp(UploadedFile file, String username) {
Are there any restrictions on the size of `file`?

2020-10-14 03:30 UTC, kofmangregory commented on src/main/User/UserController.java
> +        ctx.header("Content-Type", "application/pfp");
Is this a valid content-type?

2020-10-14 03:30 UTC, kofmangregory commented on src/main/User/UserController.java
> +        uploadPfp(file, username);
Does this function ever throw an error? Is it possible to unsuccessfully upload a profile pic? Same comment below for loading one.

2020-10-14 03:30 UTC, kofmangregory commented on src/test/UserTest/PfpTest.java
> +  @Test
Can we place tests below all functions declared in this file?

2020-10-14 03:30 UTC, kofmangregory commented on src/test/UserTest/PfpTest.java
> +    assert (get.isSuccess());
Can we ensure that the pic we got back is correct?

2020-10-16 05:33 UTC, crchong1 commented
Wait if there is a new pfp PR, what should we do about this PR? @cccyyyr

2020-10-19 06:13 UTC, closed without merging